artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1JNIeMZjP_qPGiqYxOndDBoYEapmNC9yW/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data
  unzip_dir: artifacts/data_ingestion
  s3_data_folder: data
  bucket_name: braintumor12
  train_data_path: artifacts/data_ingestion/data/train
  test_data_path: artifacts/data_ingestion/data/test





prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5




prepare_callbacks:
  root_dir: artifacts/prepare_callbacks
  tensorboard_root_log_dir: artifacts/prepare_callbacks/tensorboard_log_dir
  checkpoint_model_filepath: artifacts/prepare_callbacks/checkpoint_dir/model.h5




training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5